# -*- python -*-
Import("env")

#
# Tests
#
import glob

import lsst.tests


#If set to false tests are not run
if True:
    for fileName in glob.glob("*.cc"):
        env.Program(fileName, LIBS=env.getlibs("meas_astrom"))
    
    tests = lsst.tests.Control(env)
        
    for target in tests.run("*.py"):
        env.Depends(target, "#/python/lsst/meas/astrom/net/_netLib%s" % (env['LDMODULESUFFIX']))
