# -*- python -*-
Import('env')
import glob
import os

env.SharedLibrary(
    'meas_astrom',
    glob.glob("../src/*/*.cc"),
    LIBS=filter(lambda p: p != "meas_astrom", env.getlibs("meas_astrom")),
)
