# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11([
    "astrometry_net",
    "makeMatchStatistics",
    "matchOptimisticB",
    "polynomialTransform",
    "scaledPolynomialTransformFitter",
    "sipTransform",
])
