# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.python(['_measAstromLib'], [
    '_measAstromLib.cc',
    'makeMatchStatistics.cc',
    'matchOptimisticB/matchOptimisticB.cc',
    'polynomialTransform.cc',
    'scaledPolynomialTransformFitter.cc',
    'sipTransform.cc',
    'pessimisticPatternMatcherUtils.cc',
    'sip/createWcsWithSip.cc',
    'sip/leastSqFitter1d.cc',
    'sip/leastSqFitter2d.cc',
    'sip/matchSrcToCatalogue.cc'
])
