# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11([
    "astrometry_net/astrometry_net",
    "makeMatchStatistics",
    "matchOptimisticB/matchOptimisticB",
    "polynomialTransform",
    "scaledPolynomialTransformFitter",
    "sipTransform",
], addUnderscore=False)
