# -*- python -*-
import re
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base daf_persistence daf_data" + " " +
              "pex_exceptions pex_policy pex_logging security ndarray afw")
env.LoadableModuleIncomplete("_sipLib", Split("sipLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("meas_astrom"))
