# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base daf_persistence daf_data" + " " +
              "pex_exceptions pex_policy pex_logging security afw")
env.LoadableModuleIncomplete("_sipLib", Split("sipLib.i"), LIBS=env.getlibs("meas_astrom"))
