# -*- python -*-
import re
Import("env")

# Stolen from ap/python/lsst/ap/SConscript
pkg = env["eups_product"]
# CheckSwig() overwrites SWIGFLAGS completely, so save it's value before proceding
env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base daf_persistence daf_data" + " " +
              "pex_exceptions pex_policy pex_logging security ndarray afw")

# Append app specific SWIG flags to the environment
if env.get("MYSWIGFLAGS"):
    env.Append(SWIGFLAGS = " " + env["MYSWIGFLAGS"])

env.LoadableModuleIncomplete("_netLib", Split("netLib.i"),
                             CCFLAGS=re.sub("-Wall", "", " ".join(env['CCFLAGS'])),
                             LIBS=env.getlibs("meas_astrom"))
